INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (51, 'FRA', 'France');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (51, 'ITA', 'Italy');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (51, 'GBR', 'UK');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (51, 'SUI', 'Switzerland');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (50, 'AUT', 'Austria');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (50, 'SWE', 'Sweden');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (50, 'USA', 'USA');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (49, 'HUN', 'Hungary');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (49, 'CAN', 'Canada');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (49, 'NOR', 'Norway');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (48, 'FIN', 'Finland');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (47, 'BEL', 'Belgium');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (47, 'GRE', 'Greece');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (47, 'NED', 'Netherlands');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (46, 'AUS', 'Australia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (44, 'POL', 'Poland');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (42, 'ESP', 'Spain');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (42, 'ROU', 'Romania');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (42, 'ARG', 'Argentina');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (42, 'JPN', 'Japan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (41, 'DEN', 'Denmark');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (39, 'BUL', 'Bulgaria');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (39, 'NZL', 'New Zealand');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (39, 'TUR', 'Turkey');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (38, 'ISL', 'Iceland');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (38, 'CHI', 'Chile');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (35, 'LIE', 'Liechtenstein');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (34, 'KOR', 'South Korea');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (34, 'IND', 'India');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (34, 'GER', 'Germany');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (33, 'LUX', 'Luxembourg');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (33, 'LIB', 'Lebanon');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (32, 'TCH', 'Czech Republic');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (31, 'POR', 'Portugal');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (31, 'MEX', 'Mexico');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (30, 'BRA', 'Brazil');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (30, 'MON', 'Monaco');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (30, 'YUG', 'Serbia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (27, 'IRL', 'Ireland');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (27, 'IRI', 'Iran');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (26, 'MGL', 'Mongolia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (25, 'TPE', 'Taiwan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (25, 'PHI', 'Philippines');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (25, 'RSA', 'South Africa');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (25, 'BER', 'Bermuda');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (24, 'JAM', 'Jamaica');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (23, 'VEN', 'Venezuela');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (23, 'PUR', 'Puerto Rico');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (23, 'CHN', 'China');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (23, 'SMR', 'San Marino');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (22, 'AND', 'Andorra');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (22, 'PER', 'Peru');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (22, 'URU', 'Uruguay');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (22, 'EGY', 'Egypt');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (22, 'ISR', 'Israel');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (21, 'CUB', 'Cuba');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (21, 'EST', 'Estonia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (21, 'LAT', 'Latvia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (21, 'CRC', 'Costa Rica');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (21, 'COL', 'Colombia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (20, 'TTO', 'Trinidad');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (20, 'HKG', 'China');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (20, 'MAR', 'Morocco');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (20, 'CYP', 'Cyprus');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (19, 'PAK', 'Pakistan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (19, 'THA', 'Thailand');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (19, 'SEN', 'Senegal');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (19, 'BOL', 'Boliva');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (18, 'NEP', 'Nepal');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (18, 'PRK', 'North Korea');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (18, 'ISV', 'Virgin Islands, US');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (18, 'URS', 'Russia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (17, 'MLT', 'Malta');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (17, 'MYA', 'Myanmar');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (17, 'LTU', 'Lithuania');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (17, 'SRI', 'Sri Lanka');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (17, 'KEN', 'Kenya');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (17, 'FIJ', 'Fiji');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (17, 'GUY', 'Guyana');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (17, 'PAN', 'Panama');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (16, 'NGR', 'Nigeria');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (16, 'GUA', 'Guatemala');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (16, 'RUS', 'Russia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (16, 'HAI', 'Haiti');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (16, 'ALG', 'Algeria');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (16, 'BAH', 'Bahamas');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (15, 'AHO', 'Curacao');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (15, 'ETH', 'Ethiopia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (15, 'UGA', 'Uganda');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (15, 'CMR', 'Cameroon');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (15, 'GHA', 'Ghana');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (15, 'INA', 'Indonesia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (14, 'SLO', 'Slovenia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (14, 'DOM', 'Dominican Republic');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (14, 'TUN', 'Tunisia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (14, 'AFG', 'Afghanistan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (14, 'IRQ', 'Iraq');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (14, 'CRO', 'Croatia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (14, 'ZIM', 'Zimbabwe');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (14, 'ECU', 'Ecuador');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (13, 'MLI', 'Mali');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (13, 'MAS', 'Malaysia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (13, 'BIH', 'Bosnia and Herzegovina');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (13, 'CIV', 'Ivory Coast');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (13, 'TAN', 'Tanzania');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (13, 'ZAM', 'Zambia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (13, 'PAR', 'Paraguay');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (13, 'SYR', 'Syria');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (13, 'MAD', 'Madagascar');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'LBR', 'Liberia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'CHA', 'Chad');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'GEO', 'Georgia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'MDA', 'Moldova');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'UKR', 'Ukraine');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'CGO', 'Republic of Congo');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'BLR', 'Belarus');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'HON', 'Honduras');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'SVK', 'Slovakia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'CAY', 'Cayman Islands');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'BIZ', 'Belize');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'UZB', 'Uzbekistan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'KGZ', 'Kyrgyzstan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'ESA', 'El Salvador');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'SUR', 'Suriname');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'BAR', 'Barbados');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'KUW', 'Kuwait');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'NCA', 'Nicaragua');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'CZE', 'Czech Republic');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'ARM', 'Armenia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'KAZ', 'Kazakhstan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'SUD', 'Sudan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (12, 'NIG', 'Niger');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'SWZ', 'Swaziland');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'BEN', 'Benin');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'GUI', 'Guinea');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'SLE', 'Sierra Leone');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'FRG', 'Germany');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'GDR', 'Germany');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'IVB', 'Virgin Islands, British');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'MKD', 'Macedonia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'TOG', 'Togo');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'LES', 'Lesotho');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'KSA', 'Saudi Arabia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'ALB', 'Albania');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (11, 'AZE', 'Azerbaijan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'PNG', 'Papua New Guinea');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'JOR', 'Jordan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'TJK', 'Tajikistan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'LBA', 'Libya');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'ANT', 'Antigua');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'COD', 'Democratic Republic of the Congo');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'MAW', 'Malawi');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'TGA', 'Tonga');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'MOZ', 'Mozambique');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'BOT', 'Botswana');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'CAF', 'Central African Republic');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (10, 'GAB', 'Gabon');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'BUR', 'Burkina Faso');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'QAT', 'Qatar');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'OMA', 'Oman');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'MTN', 'Mauritania');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'RWA', 'Rwanda');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'GRN', 'Grenada');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'ANG', 'Angola');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'ASA', 'American Samoa');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'MRI', 'Mauritius');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'BRN', 'Bahrain');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'LAO', 'Laos');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'SEY', 'Seychelles');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'SOM', 'Somalia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'BAN', 'Bangladesh');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'UAE', 'United Arab Emirates');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'CAM', 'Cambodia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'BHU', 'Bhutan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'SOL', 'Solomon Islands');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'GAM', 'Gambia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'GUM', 'Guam');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'VIE', 'Vietnam');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'GEQ', 'Equatorial Guinea');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (9, 'SAM', 'Samoa');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (8, 'MDV', 'Maldives');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (8, 'COK', 'Cook Islands');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (8, 'VAN', 'Vanuatu');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (8, 'DJI', 'Djibouti');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (8, 'ARU', 'Aruba');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (8, 'VIN', 'Saint Vincent');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (7, 'YEM', 'Yemen');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (7, 'DMA', 'Dominica');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (7, 'NAM', 'Namibia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'PLE', 'Palestine');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'BDI', 'Burundi');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'SKN', 'Saint Kitts');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'SRB', 'Serbia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'GBS', 'Guinea-Bissau');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'NRU', 'Nauru');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'VNM', 'Vietnam');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'CPV', 'Cape Verde');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'COM', 'Comoros');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'SCG', 'Serbia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'LCA', 'Saint Lucia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'TKM', 'Turkmenistan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (6, 'STP', 'Sao Tome and Principe');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (5, 'FSM', 'Micronesia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (5, 'PLW', 'Palau');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (5, 'BRU', 'Brunei');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (5, 'ERI', 'Eritrea');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (5, 'IOA', 'Individual Olympic Athletes');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (5, 'TLS', 'Timor-Leste');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (5, 'MNE', 'Montenegro');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (4, 'BOH', 'Czech Republic');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (4, 'KIR', 'Kiribati');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (3, 'MHL', 'Marshall Islands');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (3, 'TUV', 'NA');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (2, 'ANZ', 'Australia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (2, 'YAR', 'Yemen');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (2, 'MAL', 'Malaysia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (2, 'EUN', 'Russia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'YMD', 'Yemen');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'UNK', 'NA');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'RHO', 'Zimbabwe');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'SSD', 'South Sudan');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'SAA', 'Germany');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'CRT', 'Greece');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'NFL', 'Canada');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'WIF', 'Trinidad');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'UAR', 'Syria');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'NBO', 'Malaysia');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'ROT', 'NA');
INSERT INTO `noc` (`total_games`, `noc`, `region`) VALUES (1, 'KOS', 'Kosovo');
