INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1896, '1896 Summer', 'Athina');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1900, '1900 Summer', 'Paris');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1904, '1904 Summer', 'St. Louis');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1906, '1906 Summer', 'Athina');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1908, '1908 Summer', 'London');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1912, '1912 Summer', 'Stockholm');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1920, '1920 Summer', 'Antwerpen');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1924, '1924 Summer', 'Paris');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1924, '1924 Winter', 'Chamonix');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1928, '1928 Summer', 'Amsterdam');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1928, '1928 Winter', 'Sankt Moritz');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1932, '1932 Summer', 'Los Angeles');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1932, '1932 Winter', 'Lake Placid');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1936, '1936 Summer', 'Berlin');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1936, '1936 Winter', 'Garmisch-Partenkirchen');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1948, '1948 Winter', 'Sankt Moritz');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1948, '1948 Summer', 'London');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1952, '1952 Winter', 'Oslo');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1952, '1952 Summer', 'Helsinki');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1956, '1956 Winter', 'Cortina d\'Ampezzo');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1956, '1956 Summer', 'Melbourne');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1960, '1960 Summer', 'Roma');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1960, '1960 Winter', 'Squaw Valley');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1964, '1964 Winter', 'Innsbruck');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1964, '1964 Summer', 'Tokyo');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1968, '1968 Summer', 'Mexico City');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1968, '1968 Winter', 'Grenoble');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1972, '1972 Summer', 'Munich');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1972, '1972 Winter', 'Sapporo');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1976, '1976 Summer', 'Montreal');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1976, '1976 Winter', 'Innsbruck');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1980, '1980 Summer', 'Moskva');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1980, '1980 Winter', 'Lake Placid');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1984, '1984 Summer', 'Los Angeles');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1984, '1984 Winter', 'Sarajevo');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1988, '1988 Summer', 'Seoul');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1988, '1988 Winter', 'Calgary');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1992, '1992 Winter', 'Albertville');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1992, '1992 Summer', 'Barcelona');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1994, '1994 Winter', 'Lillehammer');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1996, '1996 Summer', 'Atlanta');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (1998, '1998 Winter', 'Nagano');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (2000, '2000 Summer', 'Sydney');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (2002, '2002 Winter', 'Salt Lake City');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (2004, '2004 Summer', 'Athina');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (2006, '2006 Winter', 'Torino');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (2008, '2008 Summer', 'Beijing');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (2010, '2010 Winter', 'Vancouver');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (2012, '2012 Summer', 'London');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (2014, '2014 Winter', 'Sochi');
INSERT INTO `athlete_events` (`year`, `season`, `city`) VALUES (2016, '2016 Summer', 'Rio de Janeiro');
