INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('USA', 2638, 1641, 1358);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Russia', 1599, 1170, 1178);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Germany', 1301, 1195, 1260);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('UK', 678, 739, 651);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Italy', 575, 531, 531);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('France', 501, 610, 666);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Sweden', 479, 522, 535);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Canada', 463, 438, 451);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Hungary', 432, 332, 371);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Norway', 378, 361, 294);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Australia', 368, 459, 522);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('China', 351, 349, 293);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Netherlands', 287, 340, 413);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Japan', 247, 309, 357);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('South Korea', 221, 232, 185);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Finland', 198, 270, 432);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Denmark', 179, 241, 177);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Switzerland', 175, 248, 268);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Cuba', 164, 129, 116);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Romania', 161, 200, 292);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Serbia', 157, 222, 160);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('India', 138, 19, 40);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Czech Republic', 123, 262, 259);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Poland', 117, 195, 253);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Spain', 110, 243, 136);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Brazil', 109, 175, 191);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Austria', 108, 186, 156);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Belgium', 98, 197, 173);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Argentina', 91, 92, 91);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('New Zealand', 90, 56, 82);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Greece', 62, 109, 84);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Croatia', 58, 54, 37);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Bulgaria', 54, 144, 144);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Ukraine', 47, 52, 100);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Pakistan', 42, 45, 34);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Turkey', 40, 27, 28);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Jamaica', 38, 75, 44);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Kenya', 34, 41, 31);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('South Africa', 32, 47, 52);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Uruguay', 31, 2, 30);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Mexico', 30, 26, 54);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Belarus', 24, 44, 71);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Nigeria', 23, 30, 46);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Ethiopia', 22, 9, 22);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Kazakhstan', 20, 25, 32);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Cameroon', 20, 1, 1);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Iran', 18, 21, 29);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Zimbabwe', 17, 4, 1);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('North Korea', 16, 16, 35);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Slovakia', 15, 19, 13);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Bahamas', 14, 11, 15);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Estonia', 13, 12, 25);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Indonesia', 11, 17, 13);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Uzbekistan', 10, 7, 17);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Ireland', 9, 13, 13);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Thailand', 9, 8, 13);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Slovenia', 8, 13, 27);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Georgia', 8, 6, 18);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Azerbaijan', 7, 12, 25);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Trinidad', 7, 8, 22);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Egypt', 7, 8, 12);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Morocco', 6, 5, 12);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Lithuania', 6, 7, 48);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Algeria', 5, 4, 8);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Colombia', 5, 9, 14);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Portugal', 4, 11, 26);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Chile', 3, 9, 20);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Taiwan', 3, 28, 18);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Tunisia', 3, 3, 7);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Dominican Republic', 3, 2, 2);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Latvia', 3, 19, 13);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Mongolia', 2, 10, 14);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Uganda', 2, 3, 2);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Liechtenstein', 2, 2, 5);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Armenia', 2, 5, 9);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Venezuela', 2, 3, 10);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Bahrain', 1, 1, 1);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Ivory Coast', 1, 1, 1);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Syria', 1, 2, 2);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Costa Rica', 1, 1, 2);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Israel', 1, 1, 7);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Haiti', 1, 1, 5);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Tajikistan', 1, 1, 2);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Individual Olympic Athletes', 1, 1, 3);
INSERT INTO `athlete_events` (`country`, `tot_Gold_medals`, `tot_Silver_medals`, `tot_Bronze_medals`) VALUES ('Puerto Rico', 1, 2, 6);
