INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1896 Summer', 'Germany-25', 'Greece-18', 'Greece-20', 'Greece-48');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1900 Summer', 'UK-59', 'France-101', 'France-82', 'France-235');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1904 Summer', 'USA-128', 'USA-141', 'USA-125', 'USA-394');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1906 Summer', 'Greece-24', 'Greece-48', 'Greece-30', 'Greece-102');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1908 Summer', 'UK-147', 'UK-131', 'UK-90', 'UK-368');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1912 Summer', 'Sweden-103', 'UK-64', 'UK-59', 'Sweden-190');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1920 Summer', 'USA-111', 'France-71', 'Belgium-66', 'USA-194');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1924 Summer', 'USA-97', 'France-51', 'USA-49', 'USA-182');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1924 Winter', 'UK-16', 'USA-10', 'UK-11', 'UK-31');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1928 Summer', 'USA-47', 'Netherlands-29', 'Germany-41', 'USA-88');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1928 Winter', 'Canada-12', 'Sweden-13', 'Switzerland-12', 'Sweden-16');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1932 Summer', 'USA-81', 'USA-47', 'USA-61', 'USA-189');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1932 Winter', 'Canada-14', 'USA-21', 'Germany-14', 'USA-34');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1936 Summer', 'Germany-93', 'Germany-70', 'Germany-61', 'Germany-224');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1936 Winter', 'UK-12', 'Canada-13', 'USA-14', 'Norway-18');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1948 Summer', 'USA-87', 'UK-42', 'USA-35', 'USA-152');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1948 Winter', 'Canada-13', 'Czech Republic-17', 'Switzerland-19', 'Switzerland-28');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1952 Summer', 'USA-83', 'Russia-62', 'Hungary-32', 'USA-134');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1952 Winter', 'Canada-16', 'USA-25', 'Sweden-23', 'USA-30');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1956 Summer', 'Russia-68', 'Russia-46', 'Russia-55', 'Russia-169');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1956 Winter', 'Russia-26', 'USA-19', 'Canada-18', 'Russia-37');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1960 Summer', 'USA-81', 'Russia-63', 'Russia-45', 'Russia-169');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1960 Winter', 'USA-19', 'Canada-17', 'Russia-28', 'Russia-42');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1964 Summer', 'USA-95', 'Russia-63', 'Russia-51', 'Russia-174');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1964 Winter', 'Russia-30', 'Sweden-21', 'Czech Republic-17', 'Russia-47');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1968 Summer', 'USA-99', 'Russia-63', 'Russia-64', 'Russia-192');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1968 Winter', 'Russia-26', 'Czech Republic-19', 'Canada-18', 'Russia-37');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1972 Summer', 'Russia-107', 'Germany-83', 'Germany-96', 'Germany-253');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1972 Winter', 'Russia-36', 'USA-18', 'Czech Republic-19', 'Russia-45');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1976 Summer', 'Germany-123', 'Russia-95', 'Russia-77', 'Russia-286');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1976 Winter', 'Russia-38', 'Czech Republic-19', 'Germany-37', 'Germany-64');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1980 Summer', 'Russia-187', 'Russia-129', 'Russia-126', 'Russia-442');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1980 Winter', 'USA-24', 'Russia-29', 'Sweden-20', 'Russia-54');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1984 Summer', 'USA-186', 'USA-116', 'Germany-53', 'USA-352');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1984 Winter', 'Russia-29', 'Czech Republic-24', 'Sweden-21', 'Russia-56');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1988 Summer', 'Russia-134', 'Germany-91', 'Russia-99', 'Russia-300');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1988 Winter', 'Russia-40', 'Finland-22', 'Sweden-23', 'Russia-66');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1992 Summer', 'Russia-92', 'Russia-61', 'USA-85', 'USA-224');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1992 Winter', 'Russia-35', 'Canada-28', 'Czech Republic-27', 'Russia-59');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1994 Winter', 'Sweden-23', 'Canada-29', 'Finland-29', 'Germany-40');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1996 Summer', 'USA-159', 'China-70', 'Australia-84', 'USA-259');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('1998 Winter', 'USA-25', 'Russia-32', 'Finland-49', 'Finland-58');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('2000 Summer', 'USA-130', 'Australia-69', 'Germany-64', 'USA-242');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('2002 Winter', 'Canada-52', 'USA-58', 'Russia-27', 'USA-84');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('2004 Summer', 'USA-117', 'Australia-77', 'Russia-95', 'USA-263');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('2006 Winter', 'Sweden-35', 'Finland-34', 'USA-32', 'Canada-69');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('2008 Summer', 'USA-127', 'USA-110', 'USA-80', 'USA-317');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('2010 Winter', 'Canada-67', 'USA-63', 'Finland-46', 'USA-97');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('2012 Summer', 'USA-145', 'USA-57', 'Australia-59', 'USA-248');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('2014 Winter', 'Canada-59', 'Sweden-32', 'Finland-24', 'Canada-86');
INSERT INTO `athlete_events` (`games`, `Golds`, `Silvers`, `Bronzes`, `Max_medals`) VALUES ('2016 Summer', 'USA-139', 'UK-55', 'USA-71', 'USA-264');
