INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Paraguay', 17, 0, 17, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Iceland', 17, 0, 15, 2);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Montenegro', 14, 0, 14, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Malaysia', 16, 0, 11, 5);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Namibia', 4, 0, 4, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Moldova', 8, 0, 3, 5);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Philippines', 10, 0, 3, 7);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Lebanon', 4, 0, 2, 2);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Sri Lanka', 2, 0, 2, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Tanzania', 2, 0, 2, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Guatemala', 1, 0, 1, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Cyprus', 1, 0, 1, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Zambia', 2, 0, 1, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Botswana', 1, 0, 1, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Sudan', 1, 0, 1, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Tonga', 1, 0, 1, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Curacao', 1, 0, 1, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Kyrgyzstan', 3, 0, 1, 2);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Qatar', 5, 0, 1, 4);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Ghana', 23, 0, 1, 22);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Senegal', 1, 0, 1, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Virgin Islands, US', 1, 0, 1, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Niger', 2, 0, 1, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Saudi Arabia', 6, 0, 1, 5);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Gabon', 1, 0, 1, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Aruba', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Chad', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Guinea', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Malawi', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Nicaragua', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Sao Tome and Principe', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Vanuatu', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Bermuda', 1, 0, 0, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Democratic Republic of the Congo', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Iraq', 1, 0, 0, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Marshall Islands', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Papua New Guinea', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Solomon Islands', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Afghanistan', 2, 0, 0, 2);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Brunei', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Eritrea', 1, 0, 0, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Monaco', 1, 0, 0, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Rwanda', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Swaziland', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Antigua', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Central African Republic', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Madagascar', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Nauru', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('San Marino', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Turkmenistan', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Benin', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Malta', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Palestine', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Sierra Leone', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Equatorial Guinea', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Laos', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Republic of Congo', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Angola', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Cayman Islands', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Guam', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Macedonia', 1, 0, 0, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Samoa', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Belize', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Honduras', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Mali', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Palau', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Seychelles', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Yemen', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Bosnia and Herzegovina', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('El Salvador', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Micronesia', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Andorra', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Cape Verde', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Libya', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('NA', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Saint Vincent', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Togo', 1, 0, 0, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Barbados', 1, 0, 0, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Cook Islands', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Guyana', 1, 0, 0, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Maldives', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Oman', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Boliva', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Dominica', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Kuwait', 2, 0, 0, 2);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Mauritius', 1, 0, 0, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('South Sudan', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('American Samoa', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Cambodia', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Gambia', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Liberia', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Myanmar', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Saint Lucia', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Timor-Leste', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Bangladesh', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Comoros', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Guinea-Bissau', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Virgin Islands, British', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Bhutan', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Djibouti', 1, 0, 0, 1);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Kiribati', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Mauritania', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Somalia', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Albania', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Burkina Faso', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Lesotho', 0, 0, 0, 0);
INSERT INTO `athlete_events` (`region`, `medals`, `Gold`, `Silver`, `Bronze`) VALUES ('Saint Kitts', 0, 0, 0, 0);
