INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('USA', 5637, 1);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Russia', 3947, 2);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Germany', 3756, 3);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('UK', 2068, 4);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('France', 1777, 5);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Italy', 1637, 6);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Sweden', 1536, 7);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Canada', 1352, 8);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Australia', 1349, 9);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Hungary', 1135, 10);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Netherlands', 1040, 11);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Norway', 1033, 12);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('China', 993, 13);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Japan', 913, 14);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Finland', 900, 15);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Switzerland', 691, 16);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Romania', 653, 17);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Czech Republic', 644, 18);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('South Korea', 638, 19);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Denmark', 597, 20);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Poland', 565, 21);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Serbia', 539, 22);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Spain', 489, 23);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Brazil', 475, 24);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Belgium', 468, 25);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Austria', 450, 26);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Cuba', 409, 27);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Bulgaria', 342, 28);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Argentina', 274, 29);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Greece', 255, 30);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('New Zealand', 228, 31);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Ukraine', 199, 32);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('India', 197, 33);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Jamaica', 157, 34);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Croatia', 149, 35);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Belarus', 139, 36);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('South Africa', 131, 37);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Pakistan', 121, 38);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Mexico', 110, 39);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Kenya', 106, 40);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Nigeria', 99, 41);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Turkey', 95, 42);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Kazakhstan', 77, 43);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Iran', 68, 44);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('North Korea', 67, 45);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Uruguay', 63, 46);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Lithuania', 61, 47);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Ethiopia', 53, 48);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Estonia', 50, 49);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Taiwan', 49, 50);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Slovenia', 48, 51);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Slovakia', 47, 52);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Azerbaijan', 44, 53);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Indonesia', 41, 54);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Portugal', 41, 54);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Bahamas', 40, 55);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Trinidad', 37, 56);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Latvia', 35, 57);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Ireland', 35, 57);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Uzbekistan', 34, 58);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Georgia', 32, 59);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Chile', 32, 59);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Thailand', 30, 60);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Colombia', 28, 61);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Egypt', 27, 62);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Mongolia', 26, 63);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Morocco', 23, 64);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Ghana', 23, 64);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Zimbabwe', 22, 65);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Cameroon', 22, 65);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Paraguay', 17, 66);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Iceland', 17, 66);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Algeria', 17, 66);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Malaysia', 16, 67);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Armenia', 16, 67);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Venezuela', 15, 68);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Peru', 15, 68);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Montenegro', 14, 69);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Tunisia', 13, 70);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Fiji', 13, 70);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Philippines', 10, 71);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Puerto Rico', 9, 72);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Liechtenstein', 9, 72);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Israel', 9, 72);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Moldova', 8, 73);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Luxembourg', 8, 73);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Haiti', 7, 74);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Dominican Republic', 7, 74);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Uganda', 7, 74);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Saudi Arabia', 6, 75);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Individual Olympic Athletes', 5, 76);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Qatar', 5, 76);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Syria', 5, 76);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Costa Rica', 4, 77);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Namibia', 4, 77);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Vietnam', 4, 77);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Tajikistan', 4, 77);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Lebanon', 4, 77);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Panama', 3, 78);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Bahrain', 3, 78);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Kyrgyzstan', 3, 78);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Ivory Coast', 3, 78);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Niger', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Kuwait', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('United Arab Emirates', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Sri Lanka', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Burundi', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Ecuador', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Suriname', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Grenada', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Tanzania', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Zambia', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Mozambique', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Afghanistan', 2, 79);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Djibouti', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Gabon', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Senegal', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Monaco', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Kosovo', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Botswana', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Virgin Islands, US', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Bermuda', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Mauritius', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Macedonia', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Cyprus', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Eritrea', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Iraq', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Jordan', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Togo', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Curacao', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Guyana', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Tonga', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Nepal', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Guatemala', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Sudan', 1, 80);
INSERT INTO `athlete_events` (`region`, `tot_medals`, `rank`) VALUES ('Barbados', 1, 80);
