INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('New York City', 68, 1);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Los Angeles', 58, 2);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Philadelphia', 46, 3);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('San Francisco', 41, 4);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Seattle', 31, 5);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Houston', 28, 6);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Columbus', 22, 7);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Chicago', 19, 8);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('San Diego', 13, 9);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Dallas', 13, 9);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Jacksonville', 11, 10);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Aurora', 11, 10);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Springfield', 7, 11);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Jackson', 7, 11);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Cincinnati', 6, 12);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Louisville', 6, 12);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Detroit', 6, 12);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Rochester', 6, 12);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Pasadena', 6, 12);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Monroe', 5, 13);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Arlington', 5, 13);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Tucson', 5, 13);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Phoenix', 5, 13);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Huntsville', 5, 13);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Charlotte', 5, 13);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Columbia', 5, 13);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Wilmington', 5, 13);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Oceanside', 5, 13);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Fayetteville', 4, 14);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Richmond', 4, 14);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Minneapolis', 4, 14);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Newark', 4, 14);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lawrence', 4, 14);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Roswell', 4, 14);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Burlington', 4, 14);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Franklin', 4, 14);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Dover', 4, 14);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Long Beach', 4, 14);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Kent', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Providence', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Scottsdale', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Tampa', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Norwich', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Peoria', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Henderson', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Chester', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Auburn', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Mesa', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Milwaukee', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Fairfield', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Virginia Beach', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Oakland', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Concord', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('San Antonio', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('La Porte', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Fresno', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lakewood', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lancaster', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Grand Prairie', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Decatur', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Denver', 3, 15);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Saint Paul', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Dublin', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Clinton', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Buffalo', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Roseville', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Naperville', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Santa Ana', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lowell', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Saint Louis', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Brownsville', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Evanston', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Murray', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Stockton', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Vancouver', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Albuquerque', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Fort Worth', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Bristol', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Austin', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Suffolk', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Pueblo', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Saint Petersburg', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Salem', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Salinas', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Memphis', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Akron', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Mission Viejo', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Skokie', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Kenosha', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Bowling Green', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Glendale', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Murfreesboro', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lorain', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Gilbert', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Quincy', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Riverside', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Toledo', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Indianapolis', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Orem', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Raleigh', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Green Bay', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Watertown', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Troy', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Des Moines', 2, 16);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Huntington Beach', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Waynesboro', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Clarksville', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Hialeah', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('North Las Vegas', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('La Quinta', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Fremont', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Tamarac', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Cottage Grove', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Olathe', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Las Cruces', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Hackensack', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Montgomery', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Pico Rivera', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Spokane', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lincoln Park', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('New Albany', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Linden', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Irving', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Ontario', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Mesquite', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Westfield', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Taylor', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Warner Robins', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Round Rock', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Laguna Niguel', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lehi', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Saginaw', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Warwick', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Tyler', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Grapevine', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Sioux Falls', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Fort Lauderdale', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Orland Park', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Santa Clara', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('New Rochelle', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Palm Coast', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lansing', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Washington', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Jamestown', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('West Jordan', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Bloomington', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lindenhurst', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Greenville', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Greensboro', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Vallejo', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Gladstone', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Asheville', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Macon', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lake Charles', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Westland', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Carlsbad', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Hesperia', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Parma', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Broomfield', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Conroe', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Redlands', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Grove City', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Thomasville', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Daytona Beach', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Durham', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Saint Peters', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Allen', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Marion', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Arlington Heights', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lafayette', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Brentwood', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Gulfport', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Carrollton', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Independence', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Colorado Springs', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Parker', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Bossier City', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Tulsa', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Encinitas', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Melbourne', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('San Jose', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Smyrna', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Charlottesville', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Apple Valley', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Manchester', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Vineland', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Baltimore', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Mcallen', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Pembroke Pines', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Bridgeton', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Manteca', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Omaha', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Portland', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Medina', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Miami', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Olympia', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Fort Collins', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Urbandale', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lakeville', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Gastonia', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Mount Vernon', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Escondido', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Mishawaka', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Inglewood', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Trenton', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Florence', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Tallahassee', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Richardson', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Arvada', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lakeland', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Lake Elsinore', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Middletown', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Marysville', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Mobile', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Perth Amboy', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Plano', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Hamilton', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Dearborn', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Coppell', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('College Station', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Oklahoma City', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Whittier', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Las Vegas', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Cleveland', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('El Paso', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Littleton', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Cary', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Tigard', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Elmhurst', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Madison', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Chapel Hill', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Park Ridge', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Amarillo', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Atlanta', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Deltona', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Hoover', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Eagan', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Edmond', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Belleville', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Costa Mesa', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Highland Park', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Harlingen', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Laredo', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('New Brunswick', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Niagara Falls', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Boynton Beach', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Rockford', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Rochester Hills', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Murrieta', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Everett', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Salt Lake City', 1, 17);
INSERT INTO `customer` (`city`, `Total_Customer`, `rank`) VALUES ('Cranston', 1, 17);
