INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('New York City', 848, 3217, 1);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Los Angeles', 728, 2756, 2);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Philadelphia', 585, 2299, 3);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('San Francisco', 474, 1773, 4);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Seattle', 386, 1371, 5);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Houston', 379, 1425, 6);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Chicago', 310, 1153, 7);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Columbus', 236, 854, 8);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Aurora', 164, 611, 9);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Dallas', 164, 602, 9);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('San Diego', 163, 609, 10);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Jacksonville', 93, 362, 11);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Detroit', 85, 332, 12);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Rochester', 74, 279, 13);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Charlotte', 73, 275, 14);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Pasadena', 71, 248, 15);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Dover', 69, 256, 16);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Phoenix', 69, 256, 16);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Jackson', 68, 253, 17);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Springfield', 68, 282, 17);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Wilmington', 64, 271, 18);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Cincinnati', 61, 214, 19);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Louisville', 61, 239, 19);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Auburn', 60, 214, 20);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Tucson', 59, 257, 21);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Minneapolis', 59, 195, 21);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Arlington', 58, 204, 22);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Oceanside', 58, 208, 22);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('La Porte', 57, 208, 23);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Long Beach', 56, 217, 24);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Monroe', 56, 184, 24);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Mesa', 53, 178, 25);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Roswell', 52, 165, 26);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Peoria', 52, 180, 26);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Chester', 51, 185, 27);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Milwaukee', 51, 200, 27);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Salem', 51, 174, 27);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lawrence', 50, 179, 28);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('San Antonio', 49, 212, 29);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Richmond', 48, 165, 30);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Columbia', 47, 193, 31);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Concord', 46, 168, 32);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Watertown', 44, 162, 33);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Newark', 44, 158, 33);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Murray', 44, 151, 33);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Huntsville', 44, 165, 33);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Mission Viejo', 43, 186, 34);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Tampa', 42, 158, 35);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Franklin', 42, 184, 35);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Salinas', 41, 149, 36);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Denver', 40, 157, 37);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Bristol', 39, 159, 38);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Glendale', 38, 139, 39);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Grand Prairie', 37, 143, 40);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lorain', 36, 118, 41);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Fayetteville', 36, 139, 41);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Providence', 36, 142, 41);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Memphis', 35, 138, 42);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Scottsdale', 35, 144, 42);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Oakland', 34, 127, 43);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Decatur', 34, 117, 43);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Smyrna', 34, 138, 43);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Norwich', 34, 133, 43);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Henderson', 32, 119, 44);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Palm Coast', 31, 102, 45);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Akron', 31, 118, 45);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Green Bay', 31, 127, 45);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Troy', 31, 115, 45);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Pueblo', 30, 119, 46);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Kenosha', 30, 126, 46);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Saint Petersburg', 30, 121, 46);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Fresno', 30, 128, 46);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Gilbert', 29, 116, 47);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Burlington', 28, 123, 48);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Urbandale', 28, 106, 48);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Bossier City', 28, 97, 48);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Roseville', 27, 112, 49);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Riverside', 27, 107, 49);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Skokie', 27, 112, 49);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Indianapolis', 27, 115, 49);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Vancouver', 27, 120, 49);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Murfreesboro', 26, 98, 50);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Hamilton', 26, 122, 50);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Austin', 26, 91, 50);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lowell', 26, 103, 50);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Taylor', 26, 105, 50);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Fairfield', 26, 88, 50);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Cleveland', 25, 88, 51);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Toledo', 25, 96, 51);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Charlottesville', 25, 81, 51);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Madison', 25, 107, 51);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Grove City', 25, 108, 51);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Highland Park', 24, 76, 52);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Naperville', 24, 84, 52);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Montgomery', 24, 101, 52);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('New Brunswick', 24, 104, 52);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Saint Louis', 24, 99, 52);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lancaster', 24, 103, 52);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Fremont', 23, 102, 53);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Quincy', 23, 73, 53);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Dublin', 23, 80, 53);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Bowling Green', 23, 89, 53);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Orem', 23, 87, 53);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Marion', 23, 77, 53);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Greenville', 22, 94, 54);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Suffolk', 22, 71, 54);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Colorado Springs', 22, 84, 54);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Tigard', 22, 78, 54);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Broomfield', 22, 97, 54);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lakewood', 22, 81, 54);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('New Rochelle', 21, 82, 55);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Evanston', 21, 69, 55);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Des Moines', 21, 69, 55);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Carlsbad', 21, 85, 55);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Waynesboro', 21, 77, 55);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Warwick', 21, 86, 55);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Grapevine', 21, 89, 55);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Pico Rivera', 20, 69, 56);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Asheville', 20, 88, 56);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Encinitas', 20, 87, 56);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Melbourne', 20, 77, 56);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Huntington Beach', 20, 83, 56);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Daytona Beach', 20, 78, 56);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Buffalo', 20, 60, 56);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Hackensack', 19, 67, 57);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('El Paso', 19, 73, 57);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Laguna Niguel', 19, 78, 57);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Chapel Hill', 19, 74, 57);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Stockton', 19, 80, 57);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Manteca', 18, 67, 58);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Medina', 18, 77, 58);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Gastonia', 18, 92, 58);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Florence', 18, 64, 58);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Saint Paul', 18, 88, 58);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Arvada', 18, 69, 58);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Plano', 17, 62, 59);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lansing', 17, 54, 59);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Perth Amboy', 17, 47, 59);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Dearborn', 17, 66, 59);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('New Albany', 17, 58, 59);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Manchester', 17, 73, 59);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('College Station', 16, 51, 60);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Miami', 16, 69, 60);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Clinton', 16, 46, 60);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Sioux Falls', 16, 57, 60);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Fort Lauderdale', 15, 52, 61);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Marysville', 15, 74, 61);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Eagan', 15, 58, 61);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Olympia', 15, 60, 61);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Fort Collins', 15, 55, 61);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('San Jose', 15, 71, 61);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Deltona', 15, 50, 61);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Santa Clara', 14, 59, 62);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('West Jordan', 14, 58, 62);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Santa Ana', 14, 43, 62);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Mount Vernon', 14, 54, 62);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Linden', 14, 64, 62);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Hesperia', 14, 66, 62);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Trenton', 14, 53, 62);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Saginaw', 14, 64, 62);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Brownsville', 14, 55, 62);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Hialeah', 14, 66, 62);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Jamestown', 13, 50, 63);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Pembroke Pines', 13, 48, 63);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Virginia Beach', 13, 42, 63);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Olathe', 13, 40, 63);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lafayette', 13, 54, 63);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Fort Worth', 13, 56, 63);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Brentwood', 13, 53, 63);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Parker', 13, 49, 63);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Westland', 13, 54, 63);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Kent', 13, 48, 63);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Bridgeton', 12, 41, 64);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Albuquerque', 12, 66, 64);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Greensboro', 12, 51, 64);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Gladstone', 12, 47, 64);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Rochester Hills', 12, 64, 64);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Parma', 12, 33, 64);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Westfield', 12, 37, 64);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Washington', 11, 35, 65);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lindenhurst', 11, 42, 65);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lakeville', 11, 38, 65);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Irving', 11, 52, 65);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Ontario', 11, 57, 65);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Independence', 11, 30, 65);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Amarillo', 11, 38, 65);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Mobile', 10, 48, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Edmond', 10, 46, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Bloomington', 10, 34, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Boynton Beach', 10, 49, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lake Charles', 10, 31, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Mesquite', 10, 37, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Salt Lake City', 10, 54, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Redlands', 10, 39, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Vineland', 10, 39, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Atlanta', 10, 34, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Hoover', 10, 29, 66);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Omaha', 9, 43, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Costa Mesa', 9, 33, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lincoln Park', 9, 28, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Whittier', 9, 32, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Murrieta', 9, 27, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Conroe', 9, 33, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Apple Valley', 9, 25, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Thomasville', 9, 40, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lake Elsinore', 9, 35, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('La Quinta', 9, 34, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Durham', 9, 43, 67);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Tamarac', 8, 28, 68);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Las Cruces', 8, 32, 68);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Gulfport', 8, 31, 68);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Carrollton', 8, 28, 68);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Macon', 8, 36, 68);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Inglewood', 8, 26, 68);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Park Ridge', 8, 37, 68);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Allen', 8, 24, 68);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Orland Park', 7, 27, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Cottage Grove', 7, 37, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Belleville', 7, 22, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Coppell', 7, 26, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Portland', 7, 22, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Harlingen', 7, 23, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Niagara Falls', 7, 23, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Littleton', 7, 16, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Mishawaka', 7, 30, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Cranston', 7, 30, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Everett', 7, 24, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('North Las Vegas', 7, 29, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Raleigh', 7, 21, 69);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Vallejo', 6, 23, 70);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Spokane', 6, 14, 70);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Cary', 6, 15, 70);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Elmhurst', 6, 32, 70);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Tyler', 6, 22, 70);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Baltimore', 6, 29, 70);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Laredo', 5, 14, 71);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Las Vegas', 5, 18, 71);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Warner Robins', 5, 20, 71);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Clarksville', 5, 22, 71);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Mcallen', 5, 17, 71);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Saint Peters', 5, 23, 71);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Oklahoma City', 4, 12, 72);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Rockford', 4, 13, 72);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lehi', 4, 10, 72);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Arlington Heights', 4, 13, 72);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Escondido', 3, 8, 73);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Round Rock', 3, 9, 73);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Tallahassee', 3, 11, 73);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Richardson', 3, 15, 73);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Middletown', 3, 14, 73);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Tulsa', 2, 10, 74);
INSERT INTO `customer` (`city`, `Total_orders`, `Total_quantity`, `rank`) VALUES ('Lakeland', 2, 6, 74);
