INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Akron', '2017-07-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Akron', '2017-08-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Albuquerque', '2017-11-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Albuquerque', '2020-03-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Allen', '2018-04-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Amarillo', '2017-10-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Apple Valley', '2018-11-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Arlington', '2017-01-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Arlington', '2017-11-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Arlington', '2017-11-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Arlington', '2018-02-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Arlington', '2019-06-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Arlington Heights', '2019-11-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Arvada', '2018-03-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Asheville', '2017-11-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Atlanta', '2018-03-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Auburn', '2017-04-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Auburn', '2017-10-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Auburn', '2019-04-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2017-06-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2017-07-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2017-07-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2017-10-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2017-10-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2017-11-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2018-03-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2018-05-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2018-07-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2018-08-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Aurora', '2018-12-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Austin', '2017-10-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Austin', '2018-10-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Baltimore', '2017-11-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Belleville', '2017-12-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Bloomington', '2017-09-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Bossier City', '2017-01-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Bowling Green', '2017-04-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Bowling Green', '2017-10-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Boynton Beach', '2017-08-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Brentwood', '2017-11-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Bridgeton', '2017-04-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Bristol', '2017-04-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Bristol', '2017-10-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Broomfield', '2017-08-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Brownsville', '2019-01-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Brownsville', '2019-10-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Buffalo', '2017-03-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Buffalo', '2017-12-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Burlington', '2017-02-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Burlington', '2017-06-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Burlington', '2018-01-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Burlington', '2019-06-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Carlsbad', '2017-04-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Carrollton', '2019-05-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Cary', '2017-09-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chapel Hill', '2018-01-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Charlotte', '2017-07-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Charlotte', '2017-09-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Charlotte', '2017-09-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Charlotte', '2017-12-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Charlotte', '2019-03-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Charlottesville', '2017-09-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chester', '2017-06-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chester', '2018-03-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chester', '2019-08-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-02-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-03-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-03-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-04-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-05-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-06-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-06-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-07-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-07-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-09-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-09-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-10-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-10-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-11-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2017-12-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2018-08-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2018-09-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2019-01-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Chicago', '2019-06-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Cincinnati', '2017-04-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Cincinnati', '2017-05-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Cincinnati', '2017-06-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Cincinnati', '2017-07-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Cincinnati', '2017-11-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Cincinnati', '2017-12-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Clarksville', '2017-09-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Cleveland', '2017-05-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Clinton', '2017-12-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Clinton', '2018-12-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('College Station', '2018-12-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Colorado Springs', '2017-06-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbia', '2017-08-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbia', '2017-08-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbia', '2017-12-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbia', '2017-12-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbia', '2019-04-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-01-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-02-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-03-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-06-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-08-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-08-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-08-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-08-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-09-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-09-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-11-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-11-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2017-12-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2018-05-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2018-06-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2018-07-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2018-09-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2018-11-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2019-03-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2019-04-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2019-07-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Columbus', '2020-07-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Concord', '2017-02-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Concord', '2017-05-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Concord', '2017-09-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Conroe', '2018-01-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Coppell', '2018-04-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Costa Mesa', '2017-04-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Cottage Grove', '2017-12-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Cranston', '2017-10-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-02-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-06-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-06-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-06-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-07-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-09-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-10-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-11-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-11-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-12-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2017-12-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2018-04-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dallas', '2019-11-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Daytona Beach', '2017-07-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dearborn', '2017-10-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Decatur', '2017-05-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Decatur', '2017-12-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Decatur', '2018-06-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Deltona', '2017-05-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Denver', '2017-05-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Denver', '2017-05-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Denver', '2017-06-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Des Moines', '2017-09-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Des Moines', '2018-03-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Detroit', '2017-03-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Detroit', '2017-04-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Detroit', '2017-09-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Detroit', '2017-10-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Detroit', '2018-12-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Detroit', '2019-04-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dover', '2017-01-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dover', '2017-01-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dover', '2017-05-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dover', '2017-08-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dublin', '2017-03-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Dublin', '2017-12-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Durham', '2017-11-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Eagan', '2017-09-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Edmond', '2018-02-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('El Paso', '2017-06-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Elmhurst', '2019-04-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Encinitas', '2017-09-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Escondido', '2017-09-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Evanston', '2017-10-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Evanston', '2017-11-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Everett', '2017-07-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fairfield', '2017-11-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fairfield', '2019-01-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fairfield', '2019-11-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fayetteville', '2017-11-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fayetteville', '2017-12-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fayetteville', '2018-09-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fayetteville', '2019-05-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Florence', '2017-07-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fort Collins', '2017-03-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fort Lauderdale', '2018-10-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fort Worth', '2017-05-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fort Worth', '2019-07-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Franklin', '2017-03-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Franklin', '2017-06-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Franklin', '2017-10-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Franklin', '2019-12-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fremont', '2017-04-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fresno', '2017-03-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fresno', '2017-09-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Fresno', '2018-05-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Gastonia', '2017-06-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Gilbert', '2017-01-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Gilbert', '2017-05-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Gladstone', '2017-10-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Glendale', '2017-07-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Glendale', '2017-07-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Grand Prairie', '2017-08-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Grand Prairie', '2017-10-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Grand Prairie', '2018-02-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Grapevine', '2017-04-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Green Bay', '2017-02-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Green Bay', '2017-02-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Greensboro', '2017-03-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Greenville', '2017-09-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Grove City', '2017-12-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Gulfport', '2017-03-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Hackensack', '2017-03-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Hamilton', '2017-03-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Harlingen', '2018-02-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Henderson', '2017-04-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Henderson', '2017-11-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Henderson', '2018-10-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Hesperia', '2017-06-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Hialeah', '2017-12-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Highland Park', '2017-04-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Hoover', '2017-01-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-01-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-01-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-01-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-02-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-03-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-04-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-04-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-05-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-05-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-05-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-05-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-06-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-07-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-07-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-08-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-08-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-09-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-09-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-11-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-12-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2017-12-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2018-03-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2018-05-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2018-05-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2018-06-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2018-09-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2018-12-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Houston', '2019-03-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Huntington Beach', '2019-03-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Huntsville', '2017-03-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Huntsville', '2017-06-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Huntsville', '2017-10-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Huntsville', '2018-03-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Huntsville', '2018-07-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Independence', '2018-10-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Indianapolis', '2017-05-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Indianapolis', '2017-12-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Inglewood', '2017-07-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Irving', '2017-03-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jackson', '2017-02-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jackson', '2017-03-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jackson', '2017-05-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jackson', '2017-07-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jackson', '2017-12-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jackson', '2018-12-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jackson', '2019-01-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2017-04-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2017-04-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2017-05-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2017-05-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2017-07-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2017-07-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2017-09-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2017-12-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2018-04-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2020-04-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jacksonville', '2020-10-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Jamestown', '2017-11-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Kenosha', '2017-04-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Kenosha', '2018-03-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Kent', '2017-05-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Kent', '2017-12-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Kent', '2020-07-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('La Porte', '2017-04-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('La Porte', '2017-09-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('La Porte', '2018-08-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('La Quinta', '2018-02-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lafayette', '2017-09-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Laguna Niguel', '2017-03-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lake Charles', '2017-04-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lake Elsinore', '2017-03-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lakeland', '2020-10-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lakeville', '2017-06-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lakewood', '2017-06-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lakewood', '2018-06-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lakewood', '2020-09-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lancaster', '2017-04-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lancaster', '2017-06-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lancaster', '2019-02-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lansing', '2017-03-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Laredo', '2017-01-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Las Cruces', '2017-06-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Las Vegas', '2018-07-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lawrence', '2017-01-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lawrence', '2017-09-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lawrence', '2017-12-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lawrence', '2018-04-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lehi', '2018-01-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lincoln Park', '2017-09-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Linden', '2017-02-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lindenhurst', '2017-05-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Littleton', '2017-06-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Long Beach', '2017-03-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Long Beach', '2017-03-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Long Beach', '2017-04-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Long Beach', '2017-09-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lorain', '2017-02-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lorain', '2017-07-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-01-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-01-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-02-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-03-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-03-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-03-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-03-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-03-31', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-04-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-04-08', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-04-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-04-26', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-04-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-05-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-05-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-05-30', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-06-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-06-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-07-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-07-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-07-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-07-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-08-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-08-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-09-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-09-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-09-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-09-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-09-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-09-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-10-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-10-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-10-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-11-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-11-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-11-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-11-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-11-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-12-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2017-12-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2018-03-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2018-03-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2018-03-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2018-04-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2018-06-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2018-06-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2018-06-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2018-08-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2018-08-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2018-11-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2019-01-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2019-06-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2019-06-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Los Angeles', '2019-08-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Louisville', '2017-01-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Louisville', '2017-05-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Louisville', '2017-06-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Louisville', '2017-07-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Louisville', '2017-11-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Louisville', '2017-11-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lowell', '2017-05-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Lowell', '2017-09-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Macon', '2017-02-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Madison', '2017-11-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Manchester', '2017-11-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Manteca', '2017-09-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Marion', '2017-09-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Marysville', '2017-12-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Mcallen', '2017-03-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Medina', '2017-05-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Melbourne', '2017-10-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Memphis', '2017-06-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Memphis', '2018-05-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Mesa', '2017-03-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Mesa', '2017-04-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Mesa', '2018-02-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Mesquite', '2017-10-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Miami', '2017-07-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Middletown', '2018-12-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Milwaukee', '2017-10-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Milwaukee', '2018-02-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Milwaukee', '2018-03-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Minneapolis', '2017-03-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Minneapolis', '2017-08-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Minneapolis', '2017-10-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Minneapolis', '2017-11-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Mishawaka', '2017-06-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Mission Viejo', '2017-01-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Mission Viejo', '2017-04-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Mobile', '2017-05-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Monroe', '2017-03-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Monroe', '2017-09-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Monroe', '2017-11-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Monroe', '2017-11-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Monroe', '2019-04-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Montgomery', '2017-12-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Mount Vernon', '2017-04-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Murfreesboro', '2017-05-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Murfreesboro', '2017-08-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Murray', '2017-05-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Murray', '2019-06-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Murrieta', '2017-08-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Naperville', '2017-01-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Naperville', '2017-02-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New Albany', '2017-01-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New Brunswick', '2018-09-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New Rochelle', '2017-01-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-01-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-01-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-01-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-02-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-02-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-02-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-02-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-03-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-03-17', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-03-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-04-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-04-05', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-04-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-04-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-05-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-05-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-06-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-06-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-06-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-06-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-07-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-07-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-07-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-07-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-08-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-08-25', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-09-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-09-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-09-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-10-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-10-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-10-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-11-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-11-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-11-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-11-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-11-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-11-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-11-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-11-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-11-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-12-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-12-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-12-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-12-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2017-12-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-01-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-01-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-03-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-05-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-07-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-08-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-08-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-09-15', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-09-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-09-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-09-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-10-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2018-12-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2019-01-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2019-03-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2019-05-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2019-11-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('New York City', '2020-03-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Newark', '2017-03-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Newark', '2017-10-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Newark', '2017-11-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Newark', '2019-05-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Niagara Falls', '2017-03-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('North Las Vegas', '2017-08-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Norwich', '2017-03-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Norwich', '2017-09-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Norwich', '2017-12-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Oakland', '2017-09-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Oakland', '2017-12-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Oakland', '2018-08-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Oceanside', '2017-04-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Oceanside', '2017-06-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Oceanside', '2017-08-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Oceanside', '2017-09-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Oceanside', '2018-11-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Oklahoma City', '2020-03-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Olathe', '2018-08-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Olympia', '2017-06-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Omaha', '2018-04-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Ontario', '2017-03-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Orem', '2017-03-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Orem', '2017-05-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Orland Park', '2017-05-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Palm Coast', '2017-08-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Park Ridge', '2017-05-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Parker', '2018-10-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Parma', '2017-02-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Pasadena', '2017-03-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Pasadena', '2017-08-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Pasadena', '2017-09-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Pasadena', '2017-09-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Pasadena', '2017-10-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Pasadena', '2017-11-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Pembroke Pines', '2017-10-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Peoria', '2017-06-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Peoria', '2017-07-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Peoria', '2017-07-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Perth Amboy', '2017-05-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-01-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-03-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-03-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-03-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-03-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-03-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-04-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-04-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-04-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-04-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-05-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-05-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-05-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-06-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-06-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-06-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-07-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-07-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-08-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-08-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-09-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-09-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-09-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-09-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-09-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-09-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-09-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-09-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-10-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-10-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-11-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-11-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-11-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-11-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2017-12-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2018-01-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2018-03-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2018-04-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2018-04-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2018-04-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2018-06-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2018-06-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2018-07-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2018-09-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2018-10-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Philadelphia', '2019-12-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Phoenix', '2017-08-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Phoenix', '2017-09-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Phoenix', '2017-10-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Phoenix', '2017-12-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Phoenix', '2018-07-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Pico Rivera', '2017-09-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Plano', '2017-03-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Portland', '2018-08-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Providence', '2017-08-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Providence', '2017-11-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Providence', '2019-03-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Pueblo', '2017-04-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Pueblo', '2018-05-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Quincy', '2017-01-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Quincy', '2017-08-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Raleigh', '2017-05-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Raleigh', '2018-06-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Redlands', '2017-04-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Richardson', '2018-10-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Richmond', '2017-05-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Richmond', '2017-11-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Richmond', '2018-07-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Richmond', '2018-09-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Riverside', '2017-10-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Riverside', '2018-09-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Rochester', '2017-04-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Rochester', '2017-05-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Rochester', '2017-05-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Rochester', '2017-08-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Rochester', '2017-08-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Rochester', '2017-09-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Rochester Hills', '2017-12-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Rockford', '2017-03-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Roseville', '2017-01-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Roseville', '2017-04-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Roswell', '2017-01-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Roswell', '2017-08-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Roswell', '2017-11-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Roswell', '2017-12-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Round Rock', '2018-11-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Saginaw', '2017-08-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Saint Louis', '2017-03-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Saint Louis', '2017-11-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Saint Paul', '2017-03-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Saint Paul', '2018-12-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Saint Peters', '2018-04-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Saint Petersburg', '2017-05-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Saint Petersburg', '2017-08-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Salem', '2017-07-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Salem', '2017-10-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Salinas', '2017-03-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Salinas', '2018-08-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Salt Lake City', '2018-11-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Antonio', '2017-09-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Antonio', '2017-09-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Antonio', '2017-11-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2017-01-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2017-01-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2017-02-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2017-02-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2017-08-08', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2017-08-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2017-10-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2017-10-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2017-11-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2018-09-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2018-11-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Diego', '2018-11-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-01-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-02-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-02-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-03-21', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-04-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-05-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-05-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-05-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-06-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-06-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-06-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-07-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-07-12', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-07-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-08-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-08-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-08-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-08-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-08-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-09-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-09-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-09-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-09-20', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-09-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-09-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-11-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-11-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-12-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-12-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2017-12-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2018-05-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2018-12-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2018-12-25', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2019-05-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2019-05-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2019-06-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2019-11-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Francisco', '2020-06-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('San Jose', '2017-04-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Santa Ana', '2017-03-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Santa Ana', '2017-04-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Santa Clara', '2018-05-01', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Scottsdale', '2017-12-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Scottsdale', '2018-09-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Scottsdale', '2018-11-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-01-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-02-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-03-01', 3);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-03-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-04-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-04-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-05-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-05-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-05-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-07-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-07-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-08-05', 2);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-08-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-10-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-11-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-11-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-12-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-12-14', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2017-12-19', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2018-03-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2018-03-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2018-05-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2018-05-31', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2018-06-09', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2018-08-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2018-11-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2019-02-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Seattle', '2020-11-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Sioux Falls', '2017-12-02', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Skokie', '2017-10-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Skokie', '2017-11-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Smyrna', '2017-08-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Spokane', '2017-04-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Springfield', '2017-01-10', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Springfield', '2017-06-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Springfield', '2017-08-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Springfield', '2017-11-11', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Springfield', '2018-09-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Springfield', '2018-10-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Springfield', '2019-04-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Stockton', '2017-07-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Stockton', '2019-08-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Suffolk', '2018-06-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Suffolk', '2019-08-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tallahassee', '2018-12-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tamarac', '2018-03-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tampa', '2017-03-15', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tampa', '2017-06-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tampa', '2017-10-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Taylor', '2017-04-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Thomasville', '2017-03-26', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tigard', '2017-06-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Toledo', '2017-04-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Toledo', '2017-12-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Trenton', '2017-08-06', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Troy', '2018-03-16', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Troy', '2019-06-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tucson', '2017-03-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tucson', '2017-06-17', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tucson', '2017-07-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tucson', '2017-07-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tucson', '2017-11-18', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tulsa', '2017-11-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Tyler', '2019-11-24', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Urbandale', '2017-03-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Vallejo', '2017-10-04', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Vancouver', '2017-06-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Vancouver', '2018-04-30', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Vineland', '2017-01-05', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Virginia Beach', '2017-05-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Virginia Beach', '2017-09-22', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Virginia Beach', '2018-12-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Warner Robins', '2017-12-08', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Warwick', '2017-11-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Washington', '2017-06-21', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Watertown', '2017-04-12', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Watertown', '2017-09-20', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Waynesboro', '2017-05-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('West Jordan', '2017-05-13', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Westfield', '2017-04-07', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Westland', '2017-03-23', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Whittier', '2017-05-27', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Wilmington', '2017-03-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Wilmington', '2017-05-28', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Wilmington', '2017-06-03', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Wilmington', '2017-09-29', 1);
INSERT INTO `customer` (`city`, `first_order`, `number_user`) VALUES ('Wilmington', '2019-05-30', 1);
